name: "Integrate"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.4.3"
        with:
          coverage: none
          php-version: "7.4"
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --strict


      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest


      - name: Run friendsofphp/php-cs-fixer
        run: composer run format -- --config=.php_cs --diff --diff-format=udiff --dry-run --verbose

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.1', '7.2', '7.3', '7.4']
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php-version }} - ${{ matrix.stability }} Test

    steps:
      - name: Checkout
        uses: "actions/checkout@v2.3.2"

      - name: Install PHP
        uses: "shivammathur/setup-php@2.4.3"
        with:
          coverage: none
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Run tests
        run: composer test
